function A1_ap = buildA1Aperture(pack, k)

    A1_ap = [ ...
        double(pack.Ex); ...
        double(pack.Ey); ...
        double(pack.Ez); ...
        double(pack.Ex_x) / k; ...
        double(pack.Ey_x) / k; ...
        double(pack.Ez_x) / k; ...
        double(pack.Ex_y) / k; ...
        double(pack.Ey_y) / k; ...
        double(pack.Ez_y) / k; ...
        double(pack.Ex_z) / k; ...
        double(pack.Ey_z) / k; ...
        double(pack.Ez_z) / k; ...
        double(pack.Ex_xx) / k^2; ...
        double(pack.Ey_xx) / k^2; ...
        double(pack.Ez_xx) / k^2; ...
        double(pack.Ex_xy) / k^2; ...
        double(pack.Ey_xy) / k^2; ...
        double(pack.Ez_xy) / k^2; ...
        double(pack.Ex_xz) / k^2; ...
        double(pack.Ey_xz) / k^2; ...
        double(pack.Ez_xz) / k^2; ...
        double(pack.Ex_yy) / k^2; ...
        double(pack.Ey_yy) / k^2; ...
        double(pack.Ez_yy) / k^2; ...
        double(pack.Ex_yz) / k^2; ...
        double(pack.Ey_yz) / k^2; ...
        double(pack.Ez_yz) / k^2; ...
        double(pack.Ex_zz) / k^2; ...
        double(pack.Ey_zz) / k^2; ...
        double(pack.Ez_zz) / k^2 ...
    ];
end