
function A1_vsw = buildA1Vsw(OP, k)

    A1_vsw = [ ...
        OP.Efield.o; ...
        [OP.Efield.dx; OP.Efield.dy; OP.Efield.dz] / k; ...
        [OP.Efield.dxdx; OP.Efield.dxdy; OP.Efield.dxdz; ...
         OP.Efield.dydy; OP.Efield.dydz; OP.Efield.dzdz] / k^2 ...
    ];
end
